create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text,
  category text,
  description text,
  cost_price numeric,
  sale_price numeric,
  image_url text,
  active boolean,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  name text,
  stock integer,
  extra_price numeric,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id) on delete set null,
  customer_name text,
  customer_phone text,
  payment_method text,
  total_amount numeric,
  created_at timestamptz not null default timezone('utc', now()),
  total_profit numeric
);

create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales(id) on delete cascade,
  product_id bigint references public.products(id) on delete restrict,
  variant_id bigint references public.product_variants(id) on delete restrict,
  quantity integer,
  unit_price numeric,
  cost_price_snapshot numeric
);
